test:
  uri: lb://eureka-client
test2:
  uri: http://localhost:8893/test

server:
  port: 8899

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8895/eureka/
  instance:
    prefer-ip-address: true


spring:
  application:
    name: gateway-client
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: ${test.uri}
          predicates:
            - Path=/client/**   #这里的path必须与项目的server.servlet.context-path保持一致

        - id: test_source
          uri: ${test2.uri}
          predicates:
            - Path=/test/**    #这里的path必须与项目的server.servlet.context-path保持一致

#          filters:
#            - name: Hrystrix
#              args:
#                name: fallbackcmd
#                fallback: forward:/fallback
