test:
  uri: http://localhost:8891/client
test2:
  uri: http://localhost:8893/test

server:
  port: 8899

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8895/eureka/
  instance:
    prefer-ip-address: true


spring:
  application:
    name: gateway-client
  cloud:
    gateway:
      discovery:
        locator:
          #让gateway可以发现微服务，这个很重要，不然下面路由通过lb://微服务名的方式找不到服务
          enabled: true
      #路由配置
      routes:
        #id随便，保证唯一就行
        - id: eureka-client
          #方式一：
          uri: ${test.uri}
#          uri: http://localhost:8891/client
          predicates:
            #这里的path必须与项目的server.servlet.context-path保持一致
            - Path=/client/**

        #id随便，保证唯一就行
        - id: test-client
          #方式一：使用url
#          uri: ${test2.uri}
          #方式二：lb://注册的微服务名称
          uri: lb://test-client
          predicates:
            #这里的path必须与项目的server.servlet.context-path保持一致
            - Path=/test/**
