spring:
  shardingsphere:
    datasource:
      names: 'ds1'  #配置第一个数据源
      #第一个数据源连接相关信息
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
        username: root
        password: 123456
    sharding:
      tables:
        tb_order:
          actual-data-nodes: ds1.tb_order_$->{0..1}
          table-strategy:
            standard:
              precise-algorithm-class-name: com.cloud.shardingjdbc.config.MyTableShardingAlgorithm
              sharding-column: id #用id作为分片字段

    #            inline:
    #              sharding-column: id  #配置分表策略，根据id作为分片依据（分片键）
    #              algorithm-expression: tb_order_$->{0..1}
    props:
      sql:
        show: true  #打开sql输出日志