server:
  port: 8892
  servlet:
    context-path: /sharding
spring:
  application:
    name: sharding-jdbc
  profiles:
    active: sharding1

mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.cloud.clientserver.pojo

#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8895/eureka/
    webclient:
      enabled: false
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        # yml文件配置这个值，必须添加引号，如果是properties文件，就直接用*，不需要加引号
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}



#sharding:
#  jdbc:
#    datasource:
#      names: master, slave0, slave1
#      master0:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/master0
#        username: root
#        password:
#      master0slave0:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/master0slave0
#        username: root
#        password:
#      master0slave1:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/master0slave1
#        username: root
#        password:
#      master1:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/master1
#        username: root
#        password:
#      master1slave0:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/master1slave0
#        username: root
#        password:
#      master1slave1:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/master1slave1
#        username: root
#        password:
#
#    config:
#      sharding:
#        tables:
#          t_order:
#            actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
#            table-strategy:
#              inline:
#                sharding-column: order_id
#                algorithm-expression: t_order$->{order_id % 2}
#            key-generator-column-name: order_id
#          t_order_item:
#            actual-data-nodes: ds$->{0..1}.t_order_item$->{0..1}
#            table-strategy:
#              inline:
#
#      masterslave:
#        name: ms
#        master-data-source-name: master
#        slave-data-source-names: slave0, slave1
