server:
  servlet:
    context-path: /flowable
  port: 8900
spring:
  datasource:
    #&nullCatalogMeansCurrent=true 因为mysql使用schema标识库名而不是catalog，因此mysql会扫描所有的库来找表，如果其他库中有相同名称的表，activiti就以为找到了，
    #本质上这个表在当前数据库中并不存在。设置nullCatalogMeansCurrent=true，表示mysql默认当前数据库操作
    url: jdbc:mysql://localhost:3306/flowable?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: flowable

#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8895/eureka/
    webclient:
      enabled: false
  instance:
    prefer-ip-address: true