server:
  port: 8898
  servlet:
    context-path: /seata

spring:
  application:
    name: seata-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.255.225:3306/crm3?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: select
    password: Zegw252AgwG3g_wgwfsw2525

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8895/eureka/
#  instance:
#    prefer-ip-address: true

#引入seata配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: true # 是否开启数据源自动代理
  tx-service-group: default_tx_group # 需要和config.txt上传到nacos上的service.vgroupMapping.default_tx_group保持一致
  service:
    vgroup-mapping:
      default_tx_group: default
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 172.31.255.39:8848
      group: SEATA_GROUP
      #注意这里一定要用空间id
      namespace: "1577fd4b-eab7-499c-a58d-ab6500d4521a"
      username: "nacos"
      password: "nacos"
  config:
    type: nacos
    nacos:
      server-addr: 172.31.255.39:8848
      group: SEATA_GROUP
      namespace: "1577fd4b-eab7-499c-a58d-ab6500d4521a"
      username: "nacos"
      password: "nacos"