server:
  port: 8891
  servlet:
    context-path: /client

spring:
  application:
    name: eureka-client
  data:
    mongodb:
      host: localhost
      port: 27017
      database: scrm_order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8895/eureka/
  instance:
    prefer-ip-address: true
