server:
  port: 8897
  servlet:
    context-path: /rabbitmq

spring:
  application:
    name: rabbitmq
  #### rabbitmq配置信息
  #发送消息报错：Login was refused using authentication mechanism PLAIN. For details see the broker logfile
  #原因：rabbitmq从3.3.0开始禁止使用guest/guest权限通过除localhost外的访问，所以新增一个root用户
  #如果要使用ip，就不用guest，重新创建一个admin的账号密码
  rabbitmq:
    host: 192.168.157.82  # 本机ip地址
    port: 5672
    username: admin
    password: admin
    ###生产者配置
    #消息发布者确认模式
#    publisher-confirm-type: correlated
    template:
#      exchange: RETRY_TEST_EXCHANGE
      #启用强制消息投递，即生产者发送消息成功或失败，需要返回确认消息
#      mandatory: true
      ##生产者重试配置
      retry:
        # 发送重试是否可用
        enabled: true
        # 最大重试次数，默认值为 3
        max-attempts: 2
        # 第一次和第二次尝试发布或传递消息之间的间隔，默认值为 1000 毫秒
        initial-interval: 2000
        #表示时间间隔的倍数系数，默认值为 1 当进行第 n 次重试时，
        # 会将时间间隔设置为  initial-interval * multiplier^(n-1) ，用于控制重试时间间隔逐渐增加
        multiplier: 1
        # 表示时间间隔的最大值，默认值为 10000 毫秒
        max-interval: 1000
    ### 消费者配置
    listener:
      simple:
        # 是否自动启动消息的监听 默认为true
#        auto-startup: false
        # 消费消息确认模式
#        acknowledge-mode: manual
        # 批量预取条数 默认值250
        prefetch: 50
        # 批量消费的条数
        batch-size: 20
        # 并发消费最小线程数
        concurrency: 1
        #并发消费最大线程数
        max-concurrency: 1

        ## 消费失败，重试配置
        retry:
          #开启重试
          enabled: true
          #表示最大重试次数，默认为3
          max-attempts: 4   #如果为4，原来消费一次，如果失败，会重试三次，最后丢弃。
          #表示第一次重试的时间间隔，默认值为1000毫秒
          initial-interval: 1000
          #表示时间间隔的倍数系数，默认值为 1 当进行第 n 次重试时，
          # 会将时间间隔设置为  initial-interval * multiplier^(n-1) ，用于控制重试时间间隔逐渐增加
          multiplier: 1
          # 表示时间间隔的最大值，默认值为 10000 毫秒
          max-interval: 1000
          # 消息监听器是否启用无状态（stateless）重试 默认true
          stateless: true
        # 控制当消息消费失败后，RabbitMQ 是否需要将消息重新入队。该参数的默认值为 true，即消息将被重新入队
        default-requeue-rejected: true


  ### redis配置
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
#    password:
    # timeout: 5000ms

delay-queue:
  rabbitmq:
    xdelayExchange: SCRM_BASE_XDELAY_EXCHANGE
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8895/eureka/
  instance:
    prefer-ip-address: true