server:
  port: 8894
  servlet:
    context-path: /mq

spring:
  application:
    name: mq-service
  rabbitmq:
    host: 192.168.156.35
    port: 5672
    username: admin
    password: admin
  redis:
    database: 0
    # Redis服务器地址
    host: 192.168.44.156
    # Redis服务器连接端口
    port: 6379
    password: zhendaa11234
    # timeout: 5000ms
eureka:
  client:
    service-url:
      defaultZone: http://192.168.156.35:8895/eureka/
  instance:
    prefer-ip-address: true

delay-queue:
  rabbitmq:
    xdelayExchange: SCRM_BASE_XDELAY_EXCHANGE
    enabled: true

#rocketmq配置信息
rocketmq:
  #nameservice服务器地址（多个以英文逗号隔开）
  name-server: 192.168.156.35:9876
  #消费者配置
  consumer:
    #组名
    group: springCloudGroup
    #监听主题
    topic: client-topic
    #tags(监听多个tag时使用||进行分隔，如果监听所有使用*或者不填)
    tags: money > 5 #这里可以根据条件对消息进行选择性的消费
